AWSTemplateFormatVersion: 2010-09-09

## =================== DESCRIPTION =================== ##
Description: >-
  AWS CloudFormation template to host a static website on Amazon S3 + CloudFront + Route53
  - Create a S3 bucket for subdomain and configure it to host a static website
  - Create a S3 bucket for root domain and set it up to redirect requests to S3 bucket for subdomain
  - Create records in a public hosted zone in Route 53 to define how you want to route traffic on the internet for the domain and its subdomains
  - Request a public SSL/TLS certificate from AWS Certificate Manager for the domain name and all its subdomains
  - Create an Origin Access Identity that you can associate with Amazon S3 origins
  - Create a CloudFront distribution for subdomain. Point it to S3 bucket for subdomain from which CloudFront gets the files to distribute
  - Create a policy for S3 bucket for subdomain to let CloudFront OAI access S3 bucket content and deny access for non SSL access to S3 bucket
  - Create a CloudFront distribution for root domain. Point it to S3 bucket for root domain
  - Create a Route 53 record set group to route DNS traffic to CloudFront domain for both - domain and subdomain

## ===================== METADATA ===================== ##
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: DNS parameters
        Parameters:
          - p_root
          - p_sub
      - Label:
          default: AWS tag parameters
        Parameters:
          - p_unitag

## ==================== PARAMETERS ==================== ##
Parameters:
  p_root:
    Description: Specify a root domain for your website
    Type: String
  p_sub:
    Description: OPTIONAL. Specify a subdomain. You can leave it empty to skip.
    Type: String
    Default: www
  p_unitag:
    Description: Specify a unique name for tag this stack resources.
    Type: String
    Default: static-website-hosting-to-s3
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters

## ==================== MAPPINGS ==================== ##
# Mappings:

## ==================== CONDITIONS ==================== ##
# Conditions:

## =================== RESOURCES =================== ##
Resources:
  # Create a S3 bucket for subdomain and configure it to host a static website
  s3bucket-sub:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${p_sub}.${p_root}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Create a S3 bucket for root domain and set it up to redirect requests to S3 bucket for subdomain
  s3bucket-root:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref p_root
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref s3bucket-sub
          Protocol: https
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Create records in a public hosted zone in Route 53 to define how you want to route traffic on the internet for the domain and its subdomains
  r53host-zone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig: 
        Comment: !Sub Public hosted zone for ${p_root}
      Name: !Ref p_root
      HostedZoneTags: 
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Request a public SSL/TLS certificate from AWS Certificate Manager for the domain name and all its subdomains
  sslcert:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref p_root
      SubjectAlternativeNames:
        - !Sub '*.${p_root}'
      DomainValidationOptions:
        - DomainName: !Ref p_root
          HostedZoneId: !GetAtt r53host-zone.Id
      ValidationMethod: DNS
      Tags:
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Create an Origin Access Identity that you can associate with Amazon S3 origins
  cf-oai:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'OAI for S3 origins'

  # Create a CloudFront distribution for subdomain. Point it to S3 bucket for subdomain from which CloudFront gets the files to distribute
  cf-dist-sub:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution points to S3 bucket for subdomain
        Origins:
          - DomainName: !Sub '${p_sub}.${p_root}.s3.${AWS::Region}.amazonaws.com'
            Id: !Sub 'S3Origin-${p_sub}.${p_root}'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${cf-oai}'
        Aliases:
          - !Sub '${p_sub}.${p_root}'
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 60
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: !Sub 'S3Origin-${p_sub}.${p_root}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html' 
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref sslcert
          SslSupportMethod: sni-only
      Tags:
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Create a policy for S3 bucket for subdomain to let CloudFront OAI access S3 bucket content and deny access for non SSL access to S3 bucket
  policy-s3bucket-sub:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Sub '${p_sub}.${p_root}'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub 'arn:aws:s3:::${p_sub}.${p_root}/*'
          Principal:
            CanonicalUser: !GetAtt cf-oai.S3CanonicalUserId
        - Sid: AllowSSLRequestsOnly 
          Effect: Deny
          Principal: '*'
          Action: 's3:*'
          Resource:
          - !Sub 'arn:aws:s3:::${p_sub}.${p_root}'
          - !Sub 'arn:aws:s3:::${p_sub}.${p_root}/*'
          Condition:
            Bool:
              'aws:SecureTransport': false

  # Create a CloudFront distribution for root domain. Point it to S3 bucket for root domain
  cf-dist-root:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution points to S3 bucket for root domain
        Origins: 
          - DomainName: !Sub '${p_root}.s3-website-${AWS::Region}.amazonaws.com'
            Id: !Sub 'RedirectS3Origin-${p_root}' 
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: 'http-only' 
        Aliases:
          - !Sub '${p_root}'
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 60
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: !Sub 'RedirectS3Origin-${p_root}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html' 
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref sslcert
          SslSupportMethod: sni-only
      Tags:
        - Key: cf-static-web
          Value: !Ref p_unitag

  # Create a Route 53 record set group to route DNS traffic to CloudFront domain for both - domain and subdomain
  r53host-zone-records:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      Comment: Route53 record for CloudFront distributions for root domain and subdomain
      HostedZoneId: !GetAtt r53host-zone.Id
      RecordSets:
        - Name: !Sub '${p_sub}.${p_root}.'
          Type: A
          AliasTarget:
              DNSName: !GetAtt cf-dist-sub.DomainName
              HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Sub '${p_root}.'
          Type: A
          AliasTarget:
              DNSName: !GetAtt cf-dist-root.DomainName 
              HostedZoneId: Z2FDTNDATAQYW2

## ======================= OUTPUT ====================== ##
Outputs:
  outputS3WebsiteURLForRootDomain:
    Description: Amazon S3 website endpoint for root domain
    Value: !GetAtt s3bucket-root.WebsiteURL
  outputS3DomainNameForRootDomain:
    Description:  IPv4 DNS name of S3 bucket for root domain
    Value: !GetAtt s3bucket-root.DomainName
  outputS3RegionalDomainNameForRootDomain:
    Description:  Regional domain name of S3 bucket for root domain
    Value: !GetAtt s3bucket-root.RegionalDomainName 
  outputS3WebsiteURLForSubdomain:
    Description: Amazon S3 website endpoint for subdomain
    Value: !GetAtt s3bucket-sub.WebsiteURL
  outputS3DomainNameForSubdomain:
    Description:  IPv4 DNS name of S3 bucket for subdomain
    Value: !GetAtt s3bucket-sub.DomainName
  outputS3RegionalDomainNameForSubdomain:
    Description:  Regional domain name of S3 bucket for subdomain
    Value: !GetAtt s3bucket-sub.RegionalDomainName  
  outputRoute53HostedZoneId:
    Description: Public hosted zone ID
    Value: !GetAtt r53host-zone.Id 
  outputRoute53HostedZoneNameServers:
    Description: List of name servers for newly created public hosted zone
    Value: !Join [', ', !GetAtt r53host-zone.NameServers] 
  outputCertificateArn:
    Description: Issued SSL certificate Arn
    Value: !Ref sslcert
  outputCloudFrontDistributionForSubdomainId:
    Description: CloudFront distribution ID for subdomain
    Value: !Ref cf-dist-sub
  outputCloudFrontDistributionDomainNameForSubdomain:
    Description: CloudFront distribution domain name for subdomain
    Value: !GetAtt cf-dist-sub.DomainName
  outputCloudFrontDistributionForRootDomainId:
    Description: CloudFront distribution ID for root domain
    Value: !Ref cf-dist-root
  outputCloudFrontDistributionDomainNameForRootDomain:
    Description: CloudFront distribution domain name for root domain
    Value: !GetAtt cf-dist-root.DomainName  
  outputWebsiteURLForSubdomain:
    Description: Website url for subdomain
    Value: !Sub 'https://${p_sub}.${p_root}/'
  outputWebsiteURLForRootDomain:
    Description: Website url for root domain
    Value: !Sub 'https://${p_root}/'